export default {
	data: 	[{tag:"div", body:'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto', title:'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', class:'firstSquare'},
			{tag:"div", body:'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla', title:'qui est esse', class:'secondSquare'},
			{tag:"div", body:'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut', title:'ea molestias quasi exercitationem repellat qui ipsa sit aut', class:'thirdSquare'},
			{tag:"div", body:'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit', title:'eum et est occaecati', class:'firstSquare'},
			{tag:"div", body:'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque', title:'nesciunt quas odio', class:'secondSquare'},
			{tag:"div", body:'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae', title:'dolorem eum magni eos aperiam quia', class:'thirdSquare'},
			{tag:"div", body:'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas', title:'magnam facilis autem', class:'firstSquare'},
			{tag:"div", body:'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae', title:'dolorem dolore est ipsam', class:'secondSquare'},
			{tag:"div", body:'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas', title:'nesciunt iure omnis dolorem tempora et accusantium', class:'thirdSquare'},
			{tag:"div", body:'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error', title:'optio molestias id quia eum', class:'rectangle'},
			{tag:"div", body:'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi', title:'et ea vero quia laudantium autem', class:'rectangle'}
			]
}